//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrandSlamWinners.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {
        public int Id { get; set; }      
        
        //Converting first letter to capital
        private string _firstName;
        [Required]
        public string FirstName
        {
            get
            {
                if (string.IsNullOrEmpty(_firstName))
                {
                    return _firstName;
                }
                return _firstName = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(_firstName);
            }
            set
            {
                _firstName= value;
            }

        }

        
        //converting first letter to capital
        private string _surname;
        [Required]
        public string Surname
        {
            get
            {
                if (string.IsNullOrEmpty(_surname))
                {
                    return _surname;
                }
                return _surname = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(_surname);
            }

            set
            {
                _surname = value;
            }
        }
        [Required]
        [Display(Name ="Male/Female")]
        public string M_F { get; set; }

        [Display(Name ="Date of birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-mm-dd}",ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        
        //Converting Leading letter 
        private string _country;
        public string Country
        {
            get
            {
                if (string.IsNullOrEmpty(_country))
                {
                    return _country;
                }
                return _country = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(_country);
            }
            set
            {
                _country = value;
            }
        }

        [Display(Name ="Australian Open")]
        public string AusOpenYYYY { get; set; }
        [Display(Name = "French Open")]
        public string FreOpenYYYY { get; set; }
        [Display(Name ="Wimbledon")]
        public string WimOpenYYYY { get; set; }
        [Display(Name ="US Open")]
        public string USOpenYYYY { get; set; }
        public string ImageUrl { get; set; }     
        
       
    }
    
    
}
